name: test-conda-env-py3
channels:
- conda-forge
- nodefaults

dependencies:
- git
- numpy
- sympy
- pocl
- pocl-cuda
- islpy
- pyopencl
- python=3
- python-symengine
- pyfmmlib
- pyrsistent
- pyvkfft
- mpi4py
