name: test-conda-env-py3
channels:
- conda-forge
- nodefaults

dependencies:
- git
- numpy
- sympy
- pocl
- islpy
- pyopencl
- python=3
- python-symengine=0.6.0
- pyfmmlib

- pip
- pip:
    - git+https://github.com/inducer/pytools
    - git+https://gitlab.tiker.net/inducer/boxtree
    - git+https://github.com/inducer/pymbolic
    - git+https://github.com/inducer/loopy
