# http://tex.stackexchange.com/questions/11710/specify-output-directory-when-using-latexmk
$pdflatex="pdflatex -interaction nonstopmode %O %S";
$out_dir = 'out';
$pdf_mode = 1;
$pdf_previewer = 'xdg-open';

@default_files = ('expansion-notes');

$ENV{TEXINPUTS} .=':media';
