from __future__ import annotations


__copyright__ = "Copyright (C) 2012 Andreas Kloeckner"

__license__ = """
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

import logging
from collections import defaultdict
from typing import TYPE_CHECKING, overload

from typing_extensions import Self, override

import sumpy.symbolic as sym


if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence


logger = logging.getLogger(__name__)

__doc__ = """
Manipulating batches of assignments
-----------------------------------

.. autoclass:: SymbolicAssignmentCollection
"""


class _SymbolGenerator:
    taken_symbols: Mapping[str, sym.Basic]
    base_to_count: dict[str, int]

    def __init__(self, taken_symbols: Mapping[str, sym.Basic]) -> None:
        self.taken_symbols = taken_symbols
        self.base_to_count = defaultdict(lambda: 0)

    def _normalize(self, base: str) -> str:
        # Strip off any _N suffix, to avoid generating conflicting names.
        import re
        base = re.split(r"_\d+$", base)[0]
        return base if base != "" else "expr"

    def __call__(self, base: str = "expr") -> sym.Symbol:
        base = self._normalize(base)
        count = self.base_to_count[base]

        def make_id_str(base: str, count: int) -> str:
            return "{base}{suffix}".format(
                    base=base,
                    suffix="" if count == 0 else "_" + str(count - 1))

        id_str = make_id_str(base, count)
        while id_str in self.taken_symbols:
            count += 1
            id_str = make_id_str(base, count)

        self.base_to_count[base] = count + 1

        return sym.Symbol(id_str)

    def __iter__(self) -> _SymbolGenerator:
        return self

    def next(self) -> sym.Symbol:
        return self()

    def __next__(self) -> sym.Symbol:
        return self.next()


# {{{ collection of assignments

class SymbolicAssignmentCollection:
    """Represents a collection of assignments::

        a = 5*x
        b = a**2-k

    In the above, *x* and *k* are external variables, and *a* and *b* are
    variables managed by this object.

    This is a stateful object, but the only state changes allowed are additions
    to *assignments*, and corresponding updates of its lookup tables.

    Note that user code is *only* allowed to hold on to *names* generated by
    this class, but not expressions using names defined in this collection.

    .. autoattribute:: assignments
    .. automethod:: add_assignment
    .. automethod:: assign_unique
    .. automethod:: assign_temp
    .. automethod:: run_global_cse
    """

    assignments: dict[str, sym.Basic]
    """A mapping from *var_name* to expressions."""
    reversed_assignments: dict[sym.Basic, str]
    symbol_generator: _SymbolGenerator
    all_dependencies_cache: dict[str, set[sym.Symbol]]

    def __init__(self, assignments: dict[str, sym.Basic] | None = None) -> None:
        if assignments is None:
            assignments = {}

        self.assignments = assignments
        self.reversed_assignments = {v: k for (k, v) in assignments.items()}

        self.symbol_generator = _SymbolGenerator(self.assignments)
        self.all_dependencies_cache = {}

    @override
    def __str__(self) -> str:
        return "\n".join(
            f"{name} <- {expr}"
            for name, expr in self.assignments.items())

    def get_all_dependencies(self, var_name: str) -> set[sym.Symbol]:
        """Including recursive dependencies."""

        try:
            return self.all_dependencies_cache[var_name]
        except KeyError:
            pass

        if var_name not in self.assignments:
            return set()

        result: set[sym.Symbol] = set()
        for dep in self.assignments[var_name].atoms():
            if not isinstance(dep, sym.Symbol):
                continue

            dep_name = dep.name
            if dep_name in self.assignments:
                result.update(self.get_all_dependencies(dep_name))
            else:
                result.add(dep)

        self.all_dependencies_cache[var_name] = result
        return result

    def add_assignment(self,
                name: str,
                expr: sym.Basic,
                root_name: str | None = None,
                retain_name: bool = True) -> str:
        assert isinstance(name, str)
        assert name not in self.assignments

        if root_name is None:
            root_name = name

        new_expr = sym.sympify(expr)

        if not retain_name and new_expr in self.reversed_assignments:
            return self.reversed_assignments[new_expr]

        self.assignments[name] = new_expr
        self.reversed_assignments[new_expr] = name

        return name

    def assign_unique(self, name_base: str, expr: sym.Basic) -> str:
        """Assign *expr* to a new variable whose name is based on *name_base*.
        Return the new variable name.
        """
        new_name = self.symbol_generator(name_base).name

        return self.add_assignment(new_name, expr)

    def assign_temp(self, name_base: str, expr: sym.Basic) -> str:
        """If *expr* is mapped to a existing variable, then return the existing
        variable or assign *expr* to a new variable whose name is based on
        *name_base*. Return the variable name *expr* is mapped to in either case.
        """
        new_name = self.symbol_generator(name_base).name
        return self.add_assignment(new_name, expr, retain_name=False)

    @overload
    def run_global_cse(self, extra_exprs: None = None) -> Self: ...

    @overload
    def run_global_cse(self,
                extra_exprs: Sequence[sym.Expr]
            ) -> tuple[Self, Sequence[sym.Basic]]: ...

    def run_global_cse(self,
                extra_exprs: Sequence[sym.Expr] | None = None
            ) -> tuple[Self, Sequence[sym.Basic]] | Self:
        orig_extra_exprs = extra_exprs
        if extra_exprs is None:
            extra_exprs = []

        import time
        start_time = time.time()

        logger.info("common subexpression elimination: start")

        assign_names = list(self.assignments.keys())
        assign_exprs = [self.assignments[name] for name in assign_names]

        # Options here:
        # - checked_cse: if you mistrust the result of the cse.
        #   Uses maxima to verify.
        # - sym.cse: The sympy thing.
        # - sumpy.cse.cse: Based on sympy, designed to go faster.
        # from sumpy.symbolic import checked_cse

        from sumpy.cse import cse
        new_cse_assignments, new_exprs = cse(
                [*assign_exprs, *extra_exprs],
                symbols=self.symbol_generator)

        new_assign_exprs = new_exprs[:len(assign_exprs)]
        new_extra_exprs = new_exprs[len(assign_exprs):]

        result_assignments: dict[str, sym.Basic] = {}

        for name, value in new_cse_assignments:
            assert isinstance(name, sym.Symbol)
            result_assignments[name.name] = value

        result_assignments = {
            **result_assignments,
            **dict(zip(assign_names, new_assign_exprs, strict=True)),
        }

        logger.info("common subexpression elimination: done after %.2f s",
                    time.time() - start_time)

        result = type(self)(result_assignments)
        if orig_extra_exprs is None:
            return result
        else:
            return result, new_extra_exprs

# }}}

# vim: fdm=marker
